import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // <-- EN KRİTİK SATIR BU!

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Global Search Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={inter.className}>{children}</body>
    </html>
  );
}